services:
  - type: web
    name: startupiq-backend
    runtime: python
    buildCommand: pip install -r Backend/requirements.txt
    startCommand: cd Backend && gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
      - key: DEBUG
        value: "False"
